/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package UI;

import BLL.DepartmentBLL;
import BLL.OnlineCourseBLL;
import BLL.OnsiteCourseBLL;
import BLL.StudentBLL;
import BLL.StudentGradeBLL;
import Entity.Department;
import Entity.OnlineCourse;
import Entity.OnsiteCourse;
import Entity.Student;
import Entity.StudentGrade;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.sql.Date;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ankho
 */
public class StudentAddForm extends javax.swing.JDialog {

    StudentBLL stdBLL = new StudentBLL();
    StudentGradeBLL stGradeBLL = new StudentGradeBLL();
    OnlineCourseBLL cOnlineBLL = new OnlineCourseBLL();
    OnsiteCourseBLL cOnsiteBLL = new OnsiteCourseBLL();
    DepartmentBLL dBLL = new DepartmentBLL();
    StudentForm stdForm;
    String typeCourse = "Onsite";

    public StudentAddForm(StudentForm sf) {
        initComponents();
        stdForm = sf;
         ArrayList<OnsiteCourse> onsitelist;
        try {
            onsitelist = cOnsiteBLL.LoadOnsiteCourse();
            LoadCourseOnsite(onsitelist);
        } catch (SQLException ex) {
            Logger.getLogger(StudentAddForm.class.getName()).log(Level.SEVERE, null, ex);
        }
         
        EventChooseCourse();
        EventSelectCourse();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLbFirstName = new javax.swing.JLabel();
        jLbLastName = new javax.swing.JLabel();
        jtxtFistName = new javax.swing.JTextField();
        jtxtLastName = new javax.swing.JTextField();
        JLbEnrollmenDay = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLbHeader = new javax.swing.JLabel();
        buttonAdd = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        JLbEnrollmenDay1 = new javax.swing.JLabel();
        jCbCourse = new javax.swing.JComboBox<>();
        jRbOnline = new javax.swing.JRadioButton();
        infoCourse = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLbFirstName.setText("First Name: ");

        jLbLastName.setText("Last Name: ");

        JLbEnrollmenDay.setText("Enrollment Day: ");

        jLbHeader.setText("ADD STUDENT");

        buttonAdd.setText("ADD");
        buttonAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonAddMouseClicked(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });

        JLbEnrollmenDay1.setText("Course: ");

        jCbCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jRbOnline.setText("Online");

        infoCourse.setText("sadasdas");
        infoCourse.setToolTipText("");

        jLabel1.setText("Course Information");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jLbHeader))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnClose)
                                .addGap(72, 72, 72)
                                .addComponent(buttonAdd)
                                .addGap(50, 50, 50))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLbLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(JLbEnrollmenDay)
                                        .addComponent(jLbFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(JLbEnrollmenDay1))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jtxtFistName)
                                        .addComponent(jtxtLastName)
                                        .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                                        .addComponent(jCbCourse, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jRbOnline)))
                                .addComponent(infoCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLbHeader)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtFistName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLbEnrollmenDay)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLbEnrollmenDay1)
                    .addComponent(jRbOnline))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCbCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(infoCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAdd)
                    .addComponent(btnClose))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoadCourseOnline(ArrayList<OnlineCourse> list) {
        jCbCourse.removeAllItems();
        for (OnlineCourse c : list) {
            jCbCourse.addItem(c.getCourseID() + "_" + c.getTitle());
        }
    }

    private void LoadCourseOnsite(ArrayList<OnsiteCourse> list) {
        jCbCourse.removeAllItems();
        for (OnsiteCourse c : list) {
            jCbCourse.addItem(c.getCourseID() + "_" + c.getTitle());
        }
    }

    private void EventChooseCourse() {
        jRbOnline.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                if (e.getStateChange() == ItemEvent.SELECTED) {
                    try {
                        ArrayList<OnlineCourse> onlineCourses = cOnlineBLL.LoadOnlineCourse();
                        LoadCourseOnline(onlineCourses);
                        typeCourse = "Online";
                    } catch (SQLException ex) {
                        Logger.getLogger(StudentAddForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    try {
                        ArrayList<OnsiteCourse> onsiteCourses;
                        onsiteCourses = cOnsiteBLL.LoadOnsiteCourse();
                        LoadCourseOnsite(onsiteCourses);
                        typeCourse = "Onsite";
                    } catch (SQLException ex) {
                        Logger.getLogger(StudentAddForm.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
            }
        });
    }

    private void EventSelectCourse() {
        jCbCourse.addItemListener(new ItemListener() {
            @Override
            public void itemStateChanged(ItemEvent e) {
                if (e.getStateChange() == ItemEvent.SELECTED) {
                    Object a = jCbCourse.getSelectedItem();
                    String[] parts = a.toString().split("_");
                    String id = parts[0];
                    int courseID = Integer.parseInt(id);
                    if (typeCourse.equals("Online")) {
                        try {
                            OnlineCourse obj = cOnlineBLL.getOnlineCourse(courseID);
                            Department d = dBLL.getDepartment(obj.getDepartmentID());
                            obj.setDepartmentName(d.getName());
                            infoCourse.setText(obj.toString());
                        } catch (SQLException ex) {
                            Logger.getLogger(StudentAddForm.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    } else {
                        OnsiteCourse obj = cOnsiteBLL.getOnsiteCourse(courseID);
                        Department d = dBLL.getDepartment(obj.getDepartmentID());
                        obj.setDepartmentName(d.getName());
                        infoCourse.setText(obj.toString());
                    }

                }
            }
        });
    }

    private void buttonAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAddMouseClicked
        Student s = new Student();
        stdBLL.isBlank(jtxtFistName.getText());
        s.setFirstName(jtxtFistName.getText());
        stdBLL.isBlank(jtxtLastName.getText());
        s.setLastName(jtxtLastName.getText());
        java.util.Date utilDate = jDateChooser1.getDate();
        if (utilDate == null) {
            JOptionPane.showMessageDialog(null, "Please select a date", "Message", JOptionPane.ERROR_MESSAGE);
        } else {
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String formattedDate = dateFormat.format(utilDate);
            Date enrollmentDate = Date.valueOf(formattedDate);
            stdBLL.isBlank(String.valueOf(enrollmentDate));
            s.setEnrollmentDate(enrollmentDate);
        }

        try {
            if (stdBLL.addStudent(s) > 0) {
                StudentGrade stGrade = new StudentGrade();
                   // nhap o day
                stGrade.setCourseID(SOMEBITS);
                JOptionPane.showMessageDialog(this, "Complete add student", "Message", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                stdForm.loadStudent(null);
            } else {
                JOptionPane.showMessageDialog(this, "Error add student", "Message", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(StudentAddForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buttonAddMouseClicked

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnCloseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLbEnrollmenDay;
    private javax.swing.JLabel JLbEnrollmenDay1;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton buttonAdd;
    private javax.swing.JLabel infoCourse;
    private javax.swing.JComboBox<String> jCbCourse;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLbFirstName;
    private javax.swing.JLabel jLbHeader;
    private javax.swing.JLabel jLbLastName;
    private javax.swing.JRadioButton jRbOnline;
    private javax.swing.JTextField jtxtFistName;
    private javax.swing.JTextField jtxtLastName;
    // End of variables declaration//GEN-END:variables
}
